name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Versión más estable actual

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Install Capacitor and Platforms
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "MiApp" "com.miapp.id" --web-dir dist
          npx cap add android
          npx cap sync

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle' # Esto ayuda a evitar errores de archivos corruptos

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon # El modo no-daemon consume menos memoria

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mi-app-terminada
          path: android/app/build/outputs/apk/debug/app-debug.apk
